In [1]:
import numpy as np
import time

In [2]:
size = 100000000

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list end time = {end-start} seconds")

#numpy array
np_arr = np.array(py_list)
start = time.time()
#vectorization
end = time.time()
print(f"Numpy array end time = {end-start} seconds")



Python list end time = 6.562971353530884 seconds
Numpy array end time = 4.601478576660156e-05 seconds


In [3]:
import sys

print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

Python list size = 80000005600000000 bytes
numpy array size = 800000000 bytes


In [2]:
#Creation

import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr, type(arr), arr.dtype, arr.shape)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, arr2D.shape)


[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [6]:
arr1 = np.zeros((2, 3))
print(arr1, arr1.shape)

arr2 = np.ones((2, 3))
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100)
print(arr3, arr3.shape)

arr4= np.eye((5))      #identity matrix(used for operations)
print(arr4, arr4.shape)

arr5 = np.arange(1, 10, 2)      # range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4)     # evenly spaced arrays
print(arr6, arr6.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] (5, 5)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [7]:
#properties
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, arr2D.dtype, arr2D.shape, arr2D.ndim)

float_arr = arr2D.astype(np.float64)
print(float_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]] int64 (3, 3) 2
float64


In [10]:
#Operations on arrays
arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, arr.shape)

flattened = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (2, 3)
[1 2 3 4 5 6] (6,)


In [15]:
#indexing
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [19]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr[1][1])

arr1 = np.array([1,2,3,4,5])

#fancy indexing
idx = [0,1,3]
print(arr1[idx])





5
[1 2 4]


In [23]:
#boolean indexing
arr1 = np.array([1,2,3,4,5])


print(arr[arr>2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])


[3 4 5 6]
[2 4 6]
[1 3 5]


In [32]:
# Slicing
arr = np.array([1,2,3,4,5,6,7,8])

print(arr[0:8:2])       # view created(original values), python uses copy(slow)

sub_arr = arr[0:3].copy()
print(sub_arr)


[1 3 5 7]
[1 2 3]


In [34]:
# Datatypes
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.array([3 + 5j])      # Complex numbers
arr2 = np.array([6 + 2j])

print(arr1 + arr2)

arr3 = np.array(["prime", {1,2,3,4,5,6,7,8}, 3.14])
print(arr3, arr3.dtype)


[9.+7.j]
['prime' {1, 2, 3, 4, 5, 6, 7, 8} 3.14] object


In [48]:
# Multi dimensional arrays

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [53]:
#3D array

arr = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]])    # 2x3x2
print(arr, arr.shape)

print(arr[1,1,0])   # indexing

print(arr[:, 0, :])   # slicing first row both layers


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]


In [60]:
#vectorization

arr =  np.array([1,2,3,4,5,6])
arr1 =  np.array([7,8,9,10,11,12])

print(arr ** 2)
print(arr * arr1)

# BroadCasting (scaling our arrays without extra memory)
print(arr + 5)

arr =  np.array([1,2,3,4,5])
arr2 = ([[1,2,3,4,5], [1,2,3,4,5]])
print(arr + arr2)

# Broadcasting is used for normalization


[ 1  4  9 16 25 36]
[ 7 16 27 40 55 72]
[ 6  7  8  9 10 11]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [67]:
# Normalization
arr =  np.array([[1,2], [3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)



[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [70]:
# Mathematical functions
# Aggregation

arr =  np.array([1,2,3,4,5,6])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.var(arr))
print(np.median(arr))
print(np.std(arr))


21
720
1
6
0
5
3.5
2.9166666666666665
3.5
1.707825127659933


In [72]:
# Power Functions

arr =  np.array([1,2,3,4,5,6])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))



[ 1  4  9 16 25 36]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  1   8  27  64 125 216]


In [75]:
# Log func
arr =  np.array([1,2,3,4,5,6])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))



[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]


In [78]:
# Rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr =  np.array([1,2,3,-4,5,6,3])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))




3.0
4.0
3.0
3.0
[-4  1  2  3  5  6]
[-4  1  2  3  3  5  6]
[1 2 3 4 5 6 3]
