In [25]:
import torch
import torch.nn as nn

In [26]:
# input
torch.manual_seed(32)          # like random state
inputs = torch.tensor([1.0, 2.0, 3.0])


In [27]:
neuron = nn.Linear(in_features=3, out_features=1)

In [28]:
output = neuron(inputs)

In [29]:
output

tensor([-0.0604], grad_fn=<ViewBackward0>)

In [30]:
neuron.weight

Parameter containing:
tensor([[ 0.4338, -0.2632, -0.0992]], requires_grad=True)

In [31]:
neuron.bias

Parameter containing:
tensor([0.3299], requires_grad=True)

In [32]:
# verify using formula
neuron.weight @ inputs + neuron.bias

tensor([-0.0604], grad_fn=<AddBackward0>)